---
# title: Quarto 練習
subtitle: "Photoshop基礎"
author: "Suguru"
date: last-modified
theme: cosmo
# mainfont: "Microsoft JhengHei" 
format:
    # 1. 給學生的網頁講義
    html:
        output-file: index.html
        toc: true
        format-links: false
  
    # 2. 給學生的 Word 檔
    docx:
        output-file: handout.docx
        toc: true

    # 3. 給學生的 PDF 檔 (記得先跑 quarto install tinytex)
    pdf:
        output-file: handout.pdf
        toc: true
        pdf-engine: xelatex
        mainfont: "Microsoft JhengHei" 
        CJKmainfont: "Microsoft JhengHei" # 👈 關鍵 3：強制指定中文字型
        # number-sections: true

    # 4. 上課用的簡報
    revealjs:
        output-file: slides.html
        theme: default
    gfm: 
        output-file: slides.md
---
## 先備知識

::: {.content-visible when-format="gfm"}
```{=gfm}
---
```
:::

### 點陣圖與向量圖
- 點陣圖 (Pixel-based)： 由無數個小方格（像素）組成。放大後會模糊、出現鋸齒（馬賽克）。

> 適用： 照片、複雜的繪畫、光影變化豐富的圖像。

- 向量圖 (Vector)： 由數學公式運算出的線條和色塊。無限放大都不會模糊。

> 適用： Logo、文字排版、圖標。

先備觀念： 在 PS 裡放大圖片是有極限的，畫質一旦破壞通常救不回來。

---

### 基本色彩學
::::{.columns}

:::{.column width="50%"}
#### RGB
- Red,Green,Blue
- 色光三原色
- 加色
:::
:::{.column width="50%"}
#### CMYK
- Cyan,Magenta,Yellow,Black
- 色料三原色
- 減色
:::
::::

::: {.content-visible when-format="gfm"}
```{=gfm}
---
```
:::


## 基本操作

::: {.content-visible when-format="gfm"}
```{=gfm}
---
```
:::

### 縮放顯示

- 縮放顯示工具（Z）
> 搭配Alt切換放大縮小
- {{< kbd Alt >}} + 滾輪
- {{< kbd Ctrl++ >}},{{< kbd Ctrl+- >}}
- {{< kbd Ctrl+0 >}}
- {{< kbd Ctrl+1 >}}

### 移動畫面

- 手形工具（H）
- {{< kbd Space >}}空白鍵

## 選取

選取是Photoshop重要的基礎之一，不管合成還是修圖，都必須有正確的選取範圍。

### 常用選取工具

- 矩形與橢圓選取工具：當形狀是圓形或是矩形時可使用
- 套索類工具：當形狀不規則但邊緣明確時可使用
- 物件選取工具：AI智慧偵測，可直接選取人物、物體。
- 快速選取工具：自動辨別邊緣。
- 魔術棒工具：點擊顏色相近的區域，快速選取。
- 筆型工具：可選取各式邊緣的工具，繪製完成使用{{< kbd Ctrl >}}+{{< kbd Enter >}}轉換選取範圍


### 常用選取功能
- 選取主體：按一下，Photoshop 自動判斷畫面主角是誰並選取。
- 選取天空：自動把天空選起來，修風景照換天空專用。
- 顏色範圍：魔術棒加強版，可以一次選取照片中相同顏色，並且可以透過朦朧調整顏色的範圍。

### 修改選取範圍

使用選取類工具的過程中，可以對選取範圍進行修改，例如變形、增加、縮放等

- 增加選取範圍：{{< kbd Shift >}} 
- 減去選取範圍：{{< kbd Alt >}} 
- 交集選取範圍：{{< kbd Shift+Alt >}} 
- 修改選取範圍：選取／變形選取範圍
- 反轉選取範圍：選取／反轉{{< kbd Ctrl+Shift+I >}}
- 取消選取範圍：{{< kbd Ctrl+D >}}

### 儲存選取範圍

若要儲存你的選取範圍以備不時之需，可以直接存在色版內。

- 選取／儲存選取範圍

也可以直接新增遮色片當作儲存範圍

> 白色代表選取，黑色代表為沒有選取

> 若使用筆型工具選取，則會有路徑產生，路徑也可以當作選取範圍使用

### 載入選取範圍

按住{{< kbd Ctrl >}}點選遮色片、色版或路徑，即可載入選取範圍。

### 選取邊緣調整

選取／修改

- 邊界：將選取範圍變成邊界。
- 平滑：將邊緣平滑化。
- 擴張：將選取範圍往外擴張。
- 縮減：將選取範圍往內縮減。
- 羽化：羽化邊緣。

> 若邊緣為毛邊或柔邊，可以使用「選取並遮住」調整

### 變形

選取之後，可以將選取的像素複製或是變形來進行合成或修圖。
在選取範圍內按滑鼠右鍵／任意變形，或是編輯／任意變形，或是{{< kbd Ctrl+T >}}
## 影像調整

## 人像編修

### 基本修復工具
- 汙點修復筆刷
- 修復筆刷
- 修補工具
- 紅眼工具
- 仿製印章



|      |         汙點修復筆刷         |    修復筆刷    |          仿製印章          |
| ---- |:----------------------------:|:--------------:|:--------------------------:|
| 取樣 {{< kbd Alt >}}|              X               |       O        |             O              |
| 抹勻 |              O               |       O        |             X              |
| 適用 | 適合顏色差異不大的小範圍修補 | 適合大部分修復 | 適合不需要與原圖融合的修復 |

### 修掉VS修淡

```{mermaid}
---
title: 瑕疵修復
---

flowchart LR
    A[開始修圖] --> B[修掉or修淡]
    B --> |修掉| C[仿製印章or修復筆刷]
    B --> |修淡| D[仿製印章]
    C --> |顏色差異大|E[先仿製印章減少顏色差異]
    C --> |顏色差異小|F[修復筆刷]
```


### 牙齒美白
- 新增調整圖層／色相飽和度
- 將色彩換成黃色
- 明亮拉到最大，飽和度降低


### 刺青
- 大略選取刺青，並且複製到要合成的人像照片中
- 將刺青去除飽和度，並且將背景調整成純白
- 使用色彩增值，去除白色部分
- 若還有灰色的部分沒有消失，再使用色階或曲線


### 皮膚柔化

#### 適用棚拍或妝容較完整的人像
- 複製圖層（Ctrl+J）
- 濾鏡／其他／顏色快調
- 濾鏡／模糊／高斯模糊：數值約為顏色快調的⅓
- 影像／調整／負片效果（Ctrl + I）
- 混合模式：線性光源
- 加上黑色圖層遮色片，把效果全部遮住，再用白色筆刷畫出柔化部分
- 可以再用圖層透明度調節整體柔化

#### 適用於大部分人像柔化
- 複製圖層（Ctrl+J）
- 混合模式：覆蓋
- 影像／調整／負片效果（Ctrl + I）
- 濾鏡／其他／顏色快調。柔化皮膚。
- 濾鏡／模糊／高斯模糊。加上紋理，若不需要還原此步可省略，
- 加上黑色圖層遮色片，把效果全部遮住，再用白色筆刷畫出柔化部分
- 可以再用圖層透明度調節整體柔化

#### 雀斑
- 複製圖層（Ctrl+J）
- 混合模式：強烈光源
- 影像／調整／負片效果（Ctrl + I）
- 濾鏡／其他／顏色快調。調整斑點與皮膚之間的柔化
- 加上黑色圖層遮色片，把效果全部遮住，再用白色筆刷畫出柔化部分
- 可以再用圖層透明度調節整體柔化
- 可以重複上述步驟

>雀斑通常顏色不會一樣，所以通常會執行兩次到三次。
重複步驟之前可以先合併（Ctrl + Alt + E）。


#### 色板柔化
- 複製圖層（Ctrl+J）
- 切換到色版面版，找到對比度最大的色版，通常是藍色色版
- 複製藍色色版，並套用顏色快調
- 影像／運算，來源1來源2不動，混合選擇線性光源或強烈光源。
- 若對比度不夠可重複執行上一步
- 影像／調整／負片效果
- 載入該色版選取範圍
- 點擊RGB色版，回到圖層面版，將剛剛的選取範圍複製到新圖層
- 調整色階或曲線 



## 常用快捷鍵

|  快捷鍵      | 內容     |
|-----------|--------|
| Ctrl + A  | 全選     |
| Ctrl + B  | 色彩平衡   |
| Ctrl + C  | 複製     |
| Ctrl + D  | 取消選取範圍 |
| Ctrl + E  | 合併圖層   |
| Ctrl + Alt + Shift + E  | 合併可見圖層後複製   |
| Ctrl + G  | 群組圖層   |
| Ctrl + I  | 負片效果   |
| Ctrl + J  | 拷貝至新圖層 |
| Ctrl + K  | 偏好設定   |
| Ctrl + L  |  色階   |
| Ctrl + M  | 曲線    |
| Ctrl + N  | 開新檔案  |
| Ctrl + O  | 開啟舊檔  |
| Ctrl + R  | 尺標    |
| Ctrl + S  | 儲存檔案  |
| Ctrl + T  | 任意變形  |
| Ctrl + U  | 色相飽和度 |
| Ctrl + V  | 貼上    |
| Ctrl + Z  | 回復上一步 |
